name: Deploy to dev

on:
    push:
        branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2
      - run: |
          npm ci
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: 'build'
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionStringDev }}
          sync: true
